name: macOS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: "${{matrix.os}} ${{matrix.compiler}} ${{matrix.build_type}} ${{matrix.sanitizer}}"
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        compiler: [clang, gcc]
        os: [macos-12, macos-13, macos-14]
        sanitizer: [ASan, TSan, UBSan]
        include:
          - compiler: clang
            cc: clang
            cxx: clang++
            standard-libraries:
            packages: llvm@15
          - os: macos-12
            compiler: gcc
            cc: gcc-11
            cxx: g++-11
            standard-libraries:
            packages:
          - os: macos-13
            compiler: gcc
            cc: gcc-12
            cxx: g++-12
            standard-libraries: -DCMAKE_CXX_STANDARD_LIBRARIES="-Wl,-ld_classic" # Use classic linker
            packages:
          - os: macos-14
            compiler: gcc
            cc: gcc-13
            cxx: g++-13
            standard-libraries: -DCMAKE_CXX_STANDARD_LIBRARIES="-Wl,-ld_classic" # Use classic linker
            packages:
        exclude:
          - compiler: gcc
            sanitizer: TSan # Not supported

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install
      run: |
        brew install ${{matrix.packages}} cmake ninja
        ${{matrix.cc}} --version
        ${{matrix.cxx}} --version
        cmake --version
        ninja --version
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      env:
        CC: ${{matrix.cc}}
        CXX: ${{matrix.cxx}}
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DSANITIZER=${{matrix.sanitizer}} ${{matrix.standard-libraries}} -G "Ninja" -S "${{github.workspace}}"

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: |
        threads=`sysctl -n hw.logicalcpu`
        cmake --build . --config ${{matrix.build_type}} --parallel $threads --target tests

    - name: Test
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      working-directory: ${{runner.workspace}}/build
      run: |
        threads=`sysctl -n hw.logicalcpu`
        ctest --build-config ${{matrix.build_type}} --output-on-failure --parallel $threads
