name: Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: "${{matrix.os}} ${{matrix.platform}} ${{matrix.toolset}} ${{matrix.build_type}}"
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        os: [windows-2019, windows-2022]
        platform: [Win32, x64]
        toolset: [v142, v143, ClangCL]
        exclude:
          - os: windows-2019
            toolset: v143
          - os: windows-2019
            toolset: ClangCL
          - os: windows-2022
            toolset: v142

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
  
    - name: Install
      run: |
        choco install cmake
        cmake --version
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake -A ${{matrix.platform}} -T ${{matrix.toolset}} -S "${{github.workspace}}"

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: |
        $threads = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
        cmake --build . --config ${{matrix.build_type}} --parallel $threads --target tests

    - name: Test
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      working-directory: ${{runner.workspace}}/build
      run: |
        $threads = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
        ctest --build-config ${{matrix.build_type}} --output-on-failure --parallel $threads
